background {
    monitor =
    path = __HOME__/Pictures/Wallpapers/penguin.png
    blur_passes = 3
    blur_size = 8
    contrast = 0.95
    brightness = 0.80
    vibrancy = 0.05
    vibrancy_darkness = 0.0
}

general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = false
    hide_cursor = true
}

label {
    monitor =
    text = cmd[update:1000] echo "<span>$(date +\"%H:%M\")</span>"
    color = rgba(216, 222, 233, 0.70)
    font_size = 80
    font_family = Inter
    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +\"%A, %d %B\")"
    color = rgba(216, 222, 233, 0.70)
    font_size = 20
    font_family = Inter
    position = 0, -80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(00000099)
    inner_color = rgba(64727d1a)
    font_color = rgb(200, 200, 200)
    fade_on_empty = true
    font_family = Inter
    placeholder_text = <i><span foreground="#ffffff99"></span></i>
    hide_input = false
    position = 0, 60
    halign = center
    valign = bottom
}
